### ISSUE TITLE
I'd like to contribute

### ISSUE THREAD

**Issue by rmhsilva** [LispCookbook/cl-cookbook#111]
I have written a couple of articles about CL on http://lispmethods.com, and I'm wondering whether the community would be better served if they were integrated with cl-cookbook. I intend to continue writing either way :). What are your thoughts / suggestions?

PS: Thanks for the awesome work!

**Comment by vindarel** [comment]
Hi ! Nice to seeing you here :) I liked your posts, they're very clear and informative, grouping stuff that is otherwise spread around. The cookbook would definitely benefit from this kind of information :) I'm thinking specially about the "source code organization" page. However the cookbook being a cookbook, it tries to have (lots of) meaningful section headings, what this page doesn't have much. And maybe we can merge it with your "getting started" page and our "Editors Support" one. We'd have all answers at the same place.

I'm looking forward to seeing the result.

Also the cookbook already refers to other documentation or to its sources, so if your original original article is more informative or if you write something that complements what's in the cookbook we can obviously link to it.

**Comment by pnathan** [comment]
+1 to what Vindarel said.

**Comment by vindarel** [comment]
and you can watch this repo and give your remarks and your approvoal on the PRs, at least on mines :D

**Comment by rmhsilva** [comment]
Awesome, thanks. I'll have a more detailed look at the cookbook soon, and think about how I could integrate some of my stuff. I'll leave lispmethods.com up, and continue putting things there, but will also try to contribute to cl-cookbook.

Is there a TODO list anywhere, other than the issues list?

Feel free to close this thread if you want, it isn't really an issue :).

**Comment by pnathan** [comment]
@rmhsilva this is *the* todo list. I chose to focus on having the issue tracker serve as that, as it has the ability for the most context and discussion.

**Comment by rmhsilva** [comment]
@pnathan ok, thanks. I've been super busy, haven't looked at lisp stuff much. Hopefully sooon...

**Comment by pnathan** [comment]
OK. Closing this thread, @rmhsilva 

Looking forward to your contributions!
