### ISSUE TITLE
Comparison among iteration libraries

### ISSUE THREAD

**Issue by sheepduke** [LispCookbook/cl-cookbook#251]
I was looking through the iteration page.

I noticed that `iterate`, `for`, `series` and built-in `loop` are introduced.

However, for a beginner, which one should be chosen? 
The awesome-cl gives a star to `iterate`, but what is the exact advantage/disadvantages of them?

In addition, what exactly does `and unlike iterate does not require code-walking` mean in the introduction of `for`?

**Comment by phoe** [comment]
I'd advise that, for a beginner, choose `LOOP` with the related [Practical Common Lisp](http://www.gigamonkeys.com/book/loop-for-black-belts.html) chapter - simply because this is the standard (literally a part of the ANSI CL standard) and the baseline for many non-trivial (`TAGBODY` + `GO`, `DO` and family) iteration constructs in Lisp.

The code-walking part is an implementation detail. `ITERATE` works by traversing the source code that it was called in and modifying it; `FOR` works without that process.

**Comment by sheepduke** [comment]
> I'd advise that, for a beginner, choose `LOOP` with the related [Practical Common Lisp](http://www.gigamonkeys.com/book/loop-for-black-belts.html) chapter - simply because this is the standard (literally a part of the ANSI CL standard) and the baseline for many non-trivial (`TAGBODY` + `GO`, `DO` and family) iteration constructs in Lisp.
>
Reasonable. Personally I use `iterate` extensively. I did not even know
`series` before.

So I was asking if there they (`for` and `iterate`) are better than
`iterate`.

> The code-walking part is an implementation detail. `ITERATE` works by traversing the source code that it was called in and modifying it; `FOR` works without that process.
>
And? What is the problem then?

**Comment by phoe** [comment]
`ITERATE` and `FOR` are extensible where `LOOP` is not.

As for code walking, the are some subtleties that I am not competent with. Ask the Lisp Discord or `#lisp` for details.

**Comment by vindarel** [comment]
\+1 for at least trying the built-in. 

`for` has one advantage, it has the generic `over` that works with any sequence (when loop needs `… in…` for lists, `… across…`, `…on…` and others for different data structures.

ps: I suggest you ask questions on /r/learnlisp, unless you ask for improvements of the Cookbook.
